# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\SensorsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1178, 846)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(130, 110, 891, 591))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.plotGrid = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.plotGrid.setContentsMargins(0, 0, 0, 0)
        self.plotGrid.setObjectName("plotGrid")
        self.graphicsView = PlotWidget(self.gridLayoutWidget)
        self.graphicsView.setObjectName("graphicsView")
        self.plotGrid.addWidget(self.graphicsView, 0, 1, 1, 1)
        self.label_sid = QtWidgets.QLabel(self.centralwidget)
        self.label_sid.setGeometry(QtCore.QRect(160, 50, 101, 41))
        self.label_sid.setText("")
        self.label_sid.setObjectName("label_sid")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
from pyqtgraph import PlotWidget
